---
- name: 'Update environment variables, master key and restart nginx'
  hosts: web
  user: "{{ deploy_user }}"

  vars_files:
    - vars/vars.yml
    - vars/envs.yml

  tasks:
    - name: Create rbenv directory
      file:
        path: "/home/{{ deploy_user }}/{{ app_name }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Update rbenv vars
      template:
        src: templates/rbenv.j2
        dest: "/home/{{ deploy_user }}/{{ app_name }}/.rbenv-vars"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Update /etc/environment
      template:
        src: templates/env.j2
        dest: "/etc/environment"
      become: true

    - name: Create shared config directory
      file:
        path: "/home/{{ deploy_user }}/{{ app_name }}/shared/config"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Update master key
      template:
        src: templates/master.key.j2
        dest: "/home/{{ deploy_user }}/{{ app_name }}/shared/config/master.key"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
      become: true