- name: Install MySQL server
  apt:
    name:
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
      - python3-pymysql
    state: present
    update_cache: yes

- name: Set MySQL root password
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    column_case_sensitive: false

- name: Save root password in .my.cnf
  template:
    src: root_my_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: create mysql DB user
  mysql_user:
    host: "localhost"
    login_user: "root"
    login_password: "{{ db_root_password }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}%.*:ALL,GRANT"

- name: Create the production database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Copy mysql config
  template:
    src: my.cnf.j2
    dest: "/etc/mysql/my.cnf"

- name: Restart MySQL service
  service:
    name: mysql
    state: restarted


- name: Install Redis from Ubuntu repositories
  apt:
    name:
      - redis-server
      - redis-tools
    state: present
    update_cache: yes