- name: Install python pip and mysqldb
  apt:
    state: present
    name:
      - python3
      - python3-pip
      - python3-mysqldb


- name: Install pdfplumber using pip3
  pip:
    name: pdfplumber
    executable: pip3
    extra_args: --break-system-packages